name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
# Cancel older runs on the same branch/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [v0.31.0, latest]

    runs-on: ${{ matrix.os }}

    # TODO: Remove setting PAT in environment variable once CLI is publicly accessible.
    env:
      WRIFTAI_SETUP_CLI_PAT: ${{secrets.WRIFTAI_SETUP_CLI_PAT}}

    steps:
      - name: Checkout Action Repo
        uses: actions/checkout@v4

      - name: Setup wriftai CLI
        id: setup_cli 
        uses: ./
        with:
          version: ${{ matrix.version }} 

      # Ensures that the installation was successful. 
      - name: Verify CLI
        run: |
          cli_output=$(wriftai version --skip-update-check)

          if [[ "${{ matrix.version }}" == "v0.31.0" ]]; then

            if [[ "${{ steps.setup_cli.outputs.version }}" != "0.31.0" ]]; then
              echo "Expected version was not outputted."
              exit 1
            fi
            
            if [[ "$cli_output" != "âœ” wriftai 0.31.0 (f80cb7b) 2025-11-13T15:49:11Z" ]]; then
              echo "CLI output did not match."
              exit 1
            fi
          fi